apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

# Include the HelmRepository and HelmRelease files
- ../../infrastructure/helmrepos/my-helm-repo.yaml
- ../../apps/java-app/helmrelease.yaml