apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: java-app
  namespace: default
spec:
  releaseName: java-app
  chart:
    spec:
      chart: mychart
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
        namespace: flux-system
      version: 0.1.0
  interval: 1m
  values:
    image:
      repository: hbn348/myapp
      tag: latest
  kubeConfig:
    secretRef:
      name: dockerhub-secret  # Referencing the Docker Hub pull secret
  imagePullSecrets:
  - name: dockerhub-secret
